name: moserlover
favicon: null
layout_spectrum: 0.1025
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#272320'
    - '#514c48'
    - '#cecece'
    - '#8e6c53'
  brandStrength: 0.3125
  lightness: 0.5625
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
